import type { Market, ToolCategory } from '@zii/registry';
import type { Lang } from './i18n';

/** Localized string map — English required, other locales optional (fallback to en). */
export type L10n = { en: string } & Partial<Record<Lang, string>>;

export interface CatalogTool {
  id: string;
  category: ToolCategory;
  offline: boolean;
  keywords: readonly string[];
  name: L10n;
  blurb: L10n;
  /** Markets this tool belongs to. Defaults to `['global']` (shown everywhere). */
  markets?: readonly Market[];
}

/**
 * The single source of truth for the universal tool catalogue. Drives the
 * registry metadata, the localized UI labels, and the SEO prerenderer, so the
 * three never drift apart.
 */
export const CATALOG: readonly CatalogTool[] = [
  {
    id: 'pdf-merge',
    category: 'pdf',
    offline: true,
    keywords: ['pdf', 'merge', 'combine', 'join'],
    name: {
      en: 'Merge PDF',
      'zh-TW': '合併 PDF',
      'zh-HK': '合併 PDF',
      ja: 'PDF を結合',
      ko: 'PDF 병합',
      es: 'Unir PDF',
      fr: 'Fusionner des PDF',
      de: 'PDF zusammenfügen',
    },
    blurb: {
      en: 'Combine multiple PDF files into one, right in your browser. Nothing is uploaded.',
      'zh-TW': '在瀏覽器中將多個 PDF 合併為一個，完全不上傳。',
    },
  },
  {
    id: 'image-convert',
    category: 'image',
    offline: true,
    keywords: ['image', 'convert', 'png', 'jpeg', 'jpg', 'webp'],
    name: {
      en: 'Convert image',
      'zh-TW': '影像轉檔',
      'zh-HK': '圖片轉檔',
      ja: '画像を変換',
      ko: '이미지 변환',
      es: 'Convertir imagen',
      fr: 'Convertir une image',
      de: 'Bild umwandeln',
    },
    blurb: {
      en: 'Convert images between PNG, JPEG and WebP on your device.',
      'zh-TW': '在裝置上於 PNG、JPEG、WebP 之間轉換影像。',
    },
  },
  {
    id: 'qr-generate',
    category: 'generator',
    offline: true,
    keywords: ['qr', 'qrcode', 'barcode', 'generate'],
    name: {
      en: 'QR code generator',
      'zh-TW': 'QR Code 產生器',
      'zh-HK': 'QR Code 產生器',
      ja: 'QR コード生成',
      ko: 'QR 코드 생성기',
      es: 'Generador de códigos QR',
      fr: 'Générateur de QR code',
      de: 'QR-Code-Generator',
    },
    blurb: {
      en: 'Generate QR codes for text, URLs, Wi-Fi, contacts, or calendar events.',
      'zh-TW': '產生文字、網址、Wi-Fi、聯絡人或行事曆活動的 QR Code。',
    },
  },
  {
    id: 'qr-batch',
    category: 'generator',
    offline: true,
    keywords: ['qr', 'batch', 'bulk', 'zip', 'multiple', 'qrcode'],
    name: { en: 'Batch QR codes', 'zh-TW': '批次 QR Code', 'zh-HK': '批次 QR Code' },
    blurb: {
      en: 'Generate one QR PNG per line and download them as a ZIP.',
      'zh-TW': '每行一個 QR Code，打包成 ZIP 下載。',
    },
  },
  {
    id: 'image-compress',
    category: 'image',
    offline: true,
    keywords: ['image', 'compress', 'shrink', 'optimize', 'jpeg', 'quality'],
    name: {
      en: 'Compress image',
      'zh-TW': '影像壓縮',
      'zh-HK': '圖片壓縮',
      ja: '画像を圧縮',
      ko: '이미지 압축',
      es: 'Comprimir imagen',
      fr: 'Compresser une image',
      de: 'Bild komprimieren',
    },
    blurb: {
      en: 'Shrink JPEG, PNG and WebP images by re-encoding at a chosen quality.',
      'zh-TW': '以指定品質重新編碼，縮小 JPEG／PNG／WebP 影像。',
    },
  },
  {
    id: 'percent-tip',
    category: 'calc',
    offline: true,
    keywords: ['percent', 'percentage', 'tip', 'split', 'change', 'calculator'],
    name: {
      en: 'Percentage & tip',
      'zh-TW': '百分比與小費',
      'zh-HK': '百分比與貼士',
      ja: '割合・チップ計算',
      ko: '퍼센트·팁 계산',
      es: 'Porcentaje y propina',
      fr: 'Pourcentage et pourboire',
      de: 'Prozent & Trinkgeld',
    },
    blurb: {
      en: 'Percentage, percentage-change and tip-split calculator.',
      'zh-TW': '百分比、增減率與小費分攤計算機。',
    },
  },
  {
    id: 'unit-convert',
    category: 'convert',
    offline: true,
    keywords: ['unit', 'convert', 'length', 'mass', 'weight', 'temperature', 'volume'],
    name: {
      en: 'Unit converter',
      'zh-TW': '單位換算',
      'zh-HK': '單位換算',
      ja: '単位変換',
      ko: '단위 변환',
      es: 'Conversor de unidades',
      fr: "Convertisseur d'unités",
      de: 'Einheitenrechner',
    },
    blurb: {
      en: 'Convert length, mass, temperature and volume units.',
      'zh-TW': '換算長度、重量、溫度與體積單位。',
    },
  },
  {
    id: 'text-count',
    category: 'text',
    offline: true,
    keywords: ['count', 'character', 'word', 'line', 'length', 'text'],
    name: {
      en: 'Character & word count',
      'zh-TW': '字數統計',
      'zh-HK': '字數統計',
      ja: '文字数カウント',
      ko: '글자·단어 수 세기',
      es: 'Contador de caracteres y palabras',
      fr: 'Compteur de caractères et de mots',
      de: 'Zeichen- & Wortzähler',
    },
    blurb: {
      en: 'Live character, word and line counts with a CJK-aware breakdown.',
      'zh-TW': '即時統計字元、字詞與行數，並依文字系統分類。',
    },
  },
  {
    id: 'text-case',
    category: 'text',
    offline: true,
    keywords: ['case', 'camel', 'snake', 'kebab', 'title', 'upper', 'lower'],
    name: {
      en: 'Case converter',
      'zh-TW': '大小寫轉換',
      'zh-HK': '大小寫轉換',
      ja: '大文字・小文字変換',
      ko: '대소문자 변환',
      es: 'Conversor de mayúsculas',
      fr: 'Convertisseur de casse',
      de: 'Groß-/Kleinschreibung',
    },
    blurb: {
      en: 'Convert text between camelCase, snake_case, Title, UPPER and more.',
      'zh-TW': '在 camelCase、snake_case、標題、全大寫等格式間轉換。',
    },
  },
  {
    id: 'json-csv',
    category: 'dev',
    offline: true,
    keywords: ['json', 'csv', 'convert', 'data', 'table'],
    name: {
      en: 'JSON ↔ CSV',
    },
    blurb: {
      en: 'Convert an array of JSON objects to CSV and back.',
      'zh-TW': '將 JSON 物件陣列與 CSV 互相轉換。',
    },
  },
  {
    id: 'csv-clean',
    category: 'dev',
    offline: true,
    keywords: ['csv', 'clean', 'dedupe', 'trim', 'data', 'table'],
    name: { en: 'CSV cleaner', 'zh-TW': 'CSV 清理', 'zh-HK': 'CSV 清理' },
    blurb: {
      en: 'Trim fields, drop blank rows, and remove duplicates from CSV.',
      'zh-TW': '修剪欄位、移除空白列與重複列。',
    },
  },
  {
    id: 'slugify',
    category: 'text',
    offline: true,
    keywords: ['slug', 'url', 'permalink', 'seo', 'kebab'],
    name: { en: 'Slugify', 'zh-TW': 'Slug 產生器', 'zh-HK': 'Slug 產生器' },
    blurb: { en: 'Turn a title into a URL-safe slug.', 'zh-TW': '將標題轉為 URL 安全的 slug。' },
  },
  {
    id: 'lorem-ipsum',
    category: 'generator',
    offline: true,
    keywords: ['lorem', 'ipsum', 'placeholder', 'dummy', 'text', 'mockup'],
    name: { en: 'Lorem ipsum', 'zh-TW': 'Lorem ipsum', 'zh-HK': 'Lorem ipsum' },
    blurb: { en: 'Generate placeholder paragraphs for layouts.', 'zh-TW': '產生排版用假文段落。' },
  },
  {
    id: 'line-dedupe',
    category: 'text',
    offline: true,
    keywords: ['dedupe', 'duplicate', 'lines', 'unique', 'list'],
    name: { en: 'Remove duplicate lines', 'zh-TW': '移除重複行', 'zh-HK': '移除重複行' },
    blurb: { en: 'Drop repeated lines, keeping the first occurrence.', 'zh-TW': '刪除重複的行。' },
  },
  {
    id: 'sort-lines',
    category: 'text',
    offline: true,
    keywords: ['sort', 'lines', 'alphabetical', 'order', 'list'],
    name: { en: 'Sort lines', 'zh-TW': '排序行', 'zh-HK': '排序行' },
    blurb: { en: 'Sort lines A→Z, Z→A, or reverse order.', 'zh-TW': '將文字行排序或反轉。' },
  },
  {
    id: 'text-normalize',
    category: 'text',
    offline: true,
    keywords: ['trim', 'whitespace', 'clean', 'normalize', 'blank lines'],
    name: { en: 'Clean up text', 'zh-TW': '文字整理', 'zh-HK': '文字整理' },
    blurb: { en: 'Trim lines and collapse extra blank lines.', 'zh-TW': '修剪空白並合併空行。' },
  },
  {
    id: 'reverse-text',
    category: 'text',
    offline: true,
    keywords: ['reverse', 'flip', 'mirror', 'text', 'backwards'],
    name: { en: 'Reverse text', 'zh-TW': '反轉文字', 'zh-HK': '反轉文字' },
    blurb: { en: 'Reverse characters or flip line order.', 'zh-TW': '反轉字元或行順序。' },
  },
  {
    id: 'hmac',
    category: 'dev',
    offline: true,
    keywords: ['hmac', 'sha256', 'sha512', 'signature', 'auth', 'crypto'],
    name: { en: 'HMAC generator', 'zh-TW': 'HMAC 產生器', 'zh-HK': 'HMAC 產生器' },
    blurb: { en: 'Compute HMAC-SHA256 or HMAC-SHA512 with a secret key.', 'zh-TW': '以密鑰計算 HMAC 簽章。' },
  },
  {
    id: 'random-string',
    category: 'generator',
    offline: true,
    keywords: ['random', 'string', 'token', 'api key', 'generator'],
    name: { en: 'Random string', 'zh-TW': '隨機字串', 'zh-HK': '隨機字串' },
    blurb: { en: 'Generate random alphanumeric strings for tokens and IDs.', 'zh-TW': '產生隨機字串供 token 或 ID 使用。' },
  },
  {
    id: 'roman-numeral',
    category: 'calc',
    offline: true,
    keywords: ['roman', 'numeral', 'convert', 'number', 'IV', 'XL'],
    name: { en: 'Roman numerals', 'zh-TW': '羅馬數字', 'zh-HK': '羅馬數字' },
    blurb: { en: 'Convert integers 1–3999 to Roman numerals and back.', 'zh-TW': '整數與羅馬數字互轉。' },
  },
  {
    id: 'data-size',
    category: 'convert',
    offline: true,
    keywords: ['bytes', 'kb', 'mb', 'gb', 'kib', 'mib', 'data', 'size'],
    name: { en: 'Data size converter', 'zh-TW': '資料大小換算', 'zh-HK': '資料大小換算' },
    blurb: { en: 'Convert decimal KB/MB/GB and binary KiB/MiB/GiB.', 'zh-TW': '換算十進位與二進位資料大小。' },
  },
  {
    id: 'find-replace',
    category: 'text',
    offline: true,
    keywords: ['find', 'replace', 'regex', 'search', 'substitute'],
    name: { en: 'Find and replace', 'zh-TW': '尋找與取代', 'zh-HK': '尋找與取代' },
    blurb: { en: 'Replace text literally or with a regular expression.', 'zh-TW': '以字面或正則取代文字。' },
  },
  {
    id: 'extract-urls',
    category: 'text',
    offline: true,
    keywords: ['extract', 'email', 'url', 'link', 'scrape'],
    name: { en: 'Extract emails & URLs', 'zh-TW': '擷取 Email 與網址', 'zh-HK': '擷取 Email 與網址' },
    blurb: { en: 'Pull email addresses and http(s) links from text.', 'zh-TW': '從文字擷取 Email 與網址。' },
  },
  {
    id: 'rot13',
    category: 'text',
    offline: true,
    keywords: ['rot13', 'cipher', 'encode', 'decode'],
    name: { en: 'ROT13', 'zh-TW': 'ROT13', 'zh-HK': 'ROT13' },
    blurb: { en: 'Encode or decode text with ROT13.', 'zh-TW': '以 ROT13 編碼或解碼。' },
  },
  {
    id: 'shuffle-lines',
    category: 'text',
    offline: true,
    keywords: ['shuffle', 'random', 'lines', 'order'],
    name: { en: 'Shuffle lines', 'zh-TW': '隨機打亂行', 'zh-HK': '隨機打亂行' },
    blurb: { en: 'Randomly shuffle the order of lines.', 'zh-TW': '隨機打亂各行順序。' },
  },
  {
    id: 'word-frequency',
    category: 'text',
    offline: true,
    keywords: ['word', 'frequency', 'count', 'statistics', 'keyword'],
    name: { en: 'Word frequency', 'zh-TW': '詞頻統計', 'zh-HK': '詞頻統計' },
    blurb: { en: 'Count how often each word appears.', 'zh-TW': '統計各詞出現次數。' },
  },
  {
    id: 'area-convert',
    category: 'convert',
    offline: true,
    keywords: ['area', 'square', 'acre', 'hectare', 'm2', 'ft2'],
    name: { en: 'Area converter', 'zh-TW': '面積換算', 'zh-HK': '面積換算' },
    blurb: { en: 'Convert m², ft², acres and hectares.', 'zh-TW': '換算平方公尺、英畝與公頃。' },
  },
  {
    id: 'speed-convert',
    category: 'convert',
    offline: true,
    keywords: ['speed', 'kmh', 'mph', 'velocity', 'convert'],
    name: { en: 'Speed converter', 'zh-TW': '速度換算', 'zh-HK': '速度換算' },
    blurb: { en: 'Convert km/h, mph, and m/s.', 'zh-TW': '換算 km/h、mph 與 m/s。' },
  },
  {
    id: 'json-escape',
    category: 'dev',
    offline: true,
    keywords: ['json', 'escape', 'unescape', 'string', 'unicode'],
    name: { en: 'JSON string escape', 'zh-TW': 'JSON 字串跳脫', 'zh-HK': 'JSON 字串跳脫' },
    blurb: { en: 'Escape or unescape a string for JSON.', 'zh-TW': '跳脫或還原 JSON 字串。' },
  },
  {
    id: 'nanoid',
    category: 'generator',
    offline: true,
    keywords: ['nanoid', 'id', 'random', 'token', 'url-safe'],
    name: { en: 'NanoID generator', 'zh-TW': 'NanoID 產生器', 'zh-HK': 'NanoID 產生器' },
    blurb: { en: 'Generate compact URL-safe IDs.', 'zh-TW': '產生 URL 安全的短 ID。' },
  },
  {
    id: 'totp',
    category: 'generator',
    offline: true,
    keywords: ['totp', '2fa', 'authenticator', 'otp', 'mfa'],
    name: { en: 'TOTP code', 'zh-TW': 'TOTP 驗證碼', 'zh-HK': 'TOTP 驗證碼' },
    blurb: { en: 'Generate a 6-digit authenticator code from a base32 secret.', 'zh-TW': '由 Base32 密鑰產生 6 位驗證碼。' },
  },
  {
    id: 'trim-lines',
    category: 'text',
    offline: true,
    keywords: ['trim', 'whitespace', 'lines', 'clean'],
    name: { en: 'Trim lines', 'zh-TW': '修剪行空白', 'zh-HK': '修剪行空白' },
    blurb: { en: 'Remove leading and trailing whitespace from each line.', 'zh-TW': '移除每一行開頭與結尾的空白。' },
  },
  {
    id: 'remove-empty-lines',
    category: 'text',
    offline: true,
    keywords: ['empty', 'blank', 'lines', 'remove'],
    name: { en: 'Remove empty lines', 'zh-TW': '移除空行', 'zh-HK': '移除空行' },
    blurb: { en: 'Delete blank or whitespace-only lines.', 'zh-TW': '刪除空白或只有空格的行。' },
  },
  {
    id: 'number-lines',
    category: 'text',
    offline: true,
    keywords: ['number', 'lines', 'prefix', 'enumerate'],
    name: { en: 'Number lines', 'zh-TW': '行號', 'zh-HK': '行號' },
    blurb: { en: 'Prefix each line with a line number.', 'zh-TW': '為每一行加上行號前綴。' },
  },
  {
    id: 'text-wrap',
    category: 'text',
    offline: true,
    keywords: ['wrap', 'word', 'line', 'width', 'break'],
    name: { en: 'Word wrap', 'zh-TW': '自動換行', 'zh-HK': '自動換行' },
    blurb: { en: 'Wrap text to a maximum line width.', 'zh-TW': '依字元寬度自動換行。' },
  },
  {
    id: 'morse-code',
    category: 'text',
    offline: true,
    keywords: ['morse', 'code', 'encode', 'decode', 'telegraph'],
    name: { en: 'Morse code', 'zh-TW': '摩斯電碼', 'zh-HK': '摩斯電碼' },
    blurb: { en: 'Encode or decode International Morse code.', 'zh-TW': '編碼或解碼國際摩斯電碼。' },
  },
  {
    id: 'binary-text',
    category: 'dev',
    offline: true,
    keywords: ['binary', 'text', 'encode', 'decode', 'bits'],
    name: { en: 'Text ↔ binary', 'zh-TW': '文字 ↔ 二進位', 'zh-HK': '文字 ↔ 二進位' },
    blurb: { en: 'Convert text to 8-bit binary and back.', 'zh-TW': '將文字轉為 8 位元二進位或還原。' },
  },
  {
    id: 'levenshtein',
    category: 'dev',
    offline: true,
    keywords: ['levenshtein', 'distance', 'edit', 'compare', 'string'],
    name: { en: 'Levenshtein distance', 'zh-TW': '編輯距離', 'zh-HK': '編輯距離' },
    blurb: { en: 'Count minimum single-character edits between two strings.', 'zh-TW': '計算兩字串的最少單字元編輯次數。' },
  },
  {
    id: 'strip-html',
    category: 'dev',
    offline: true,
    keywords: ['html', 'strip', 'tags', 'plain', 'text'],
    name: { en: 'Strip HTML', 'zh-TW': '移除 HTML', 'zh-HK': '移除 HTML' },
    blurb: { en: 'Remove HTML tags and decode entities to plain text.', 'zh-TW': '移除 HTML 標籤並解碼實體為純文字。' },
  },
  {
    id: 'pressure-convert',
    category: 'convert',
    offline: true,
    keywords: ['pressure', 'bar', 'psi', 'pascal', 'atm'],
    name: { en: 'Pressure converter', 'zh-TW': '壓力換算', 'zh-HK': '壓力換算' },
    blurb: { en: 'Convert Pa, bar, psi, atm, and mmHg.', 'zh-TW': '換算 Pa、bar、psi、atm 與 mmHg。' },
  },
  {
    id: 'timestamp-convert',
    category: 'dev',
    offline: true,
    keywords: ['unix', 'timestamp', 'epoch', 'iso', 'date'],
    name: { en: 'Unix timestamp', 'zh-TW': 'Unix 時間戳', 'zh-HK': 'Unix 時間戳' },
    blurb: { en: 'Convert between Unix timestamps and ISO 8601 dates.', 'zh-TW': '在 Unix 時間戳與 ISO 8601 日期之間轉換。' },
  },
  {
    id: 'repeat-text',
    category: 'text',
    offline: true,
    keywords: ['repeat', 'duplicate', 'copy', 'string', 'times'],
    name: { en: 'Repeat text', 'zh-TW': '重複文字', 'zh-HK': '重複文字' },
    blurb: { en: 'Repeat a string with an optional separator.', 'zh-TW': '將字串重複指定次數，可選分隔符。' },
  },
  {
    id: 'join-lines',
    category: 'text',
    offline: true,
    keywords: ['join', 'lines', 'delimiter', 'merge', 'concat'],
    name: { en: 'Join lines', 'zh-TW': '合併行', 'zh-HK': '合併行' },
    blurb: { en: 'Join multiple lines with a custom delimiter.', 'zh-TW': '以自訂分隔符合併多行。' },
  },
  {
    id: 'split-text',
    category: 'text',
    offline: true,
    keywords: ['split', 'delimiter', 'separate', 'lines'],
    name: { en: 'Split to lines', 'zh-TW': '分割成行', 'zh-HK': '分割成行' },
    blurb: { en: 'Split text by a delimiter into separate lines.', 'zh-TW': '依分隔符將文字分割成多行。' },
  },
  {
    id: 'caesar-cipher',
    category: 'text',
    offline: true,
    keywords: ['caesar', 'cipher', 'shift', 'encode', 'decode'],
    name: { en: 'Caesar cipher', 'zh-TW': '凱薩密碼', 'zh-HK': '凱薩密碼' },
    blurb: { en: 'Shift letters by a chosen amount (1–25).', 'zh-TW': '將字母位移指定格數（1–25）。' },
  },
  {
    id: 'remove-diacritics',
    category: 'text',
    offline: true,
    keywords: ['diacritics', 'accent', 'strip', 'normalize', 'ascii'],
    name: { en: 'Remove diacritics', 'zh-TW': '移除變音符', 'zh-HK': '移除變音符' },
    blurb: { en: 'Strip accents and diacritic marks from text.', 'zh-TW': '移除文字中的重音與變音符號。' },
  },
  {
    id: 'palindrome-check',
    category: 'text',
    offline: true,
    keywords: ['palindrome', 'reverse', 'check', 'symmetry'],
    name: { en: 'Palindrome checker', 'zh-TW': '回文檢查', 'zh-HK': '回文檢查' },
    blurb: { en: 'Check if text reads the same forwards and backwards.', 'zh-TW': '檢查文字是否正讀反讀相同。' },
  },
  {
    id: 'grep-lines',
    category: 'dev',
    offline: true,
    keywords: ['grep', 'filter', 'regex', 'lines', 'search'],
    name: { en: 'Grep lines', 'zh-TW': '篩選行', 'zh-HK': '篩選行' },
    blurb: { en: 'Keep lines matching a regular expression.', 'zh-TW': '保留符合正則表達式的行。' },
  },
  {
    id: 'indent-lines',
    category: 'dev',
    offline: true,
    keywords: ['indent', 'outdent', 'spaces', 'format', 'code'],
    name: { en: 'Indent lines', 'zh-TW': '縮排行', 'zh-HK': '縮排行' },
    blurb: { en: 'Add or remove leading spaces on each line.', 'zh-TW': '增加或減少每行開頭的空格。' },
  },
  {
    id: 'energy-convert',
    category: 'convert',
    offline: true,
    keywords: ['energy', 'joule', 'calorie', 'kwh', 'btu'],
    name: { en: 'Energy converter', 'zh-TW': '能量換算', 'zh-HK': '能量換算' },
    blurb: { en: 'Convert joules, calories, watt-hours, and BTU.', 'zh-TW': '換算焦耳、卡路里、瓦時與 BTU。' },
  },
  {
    id: 'duration-format',
    category: 'dev',
    offline: true,
    keywords: ['duration', 'seconds', 'time', 'format', 'hms'],
    name: { en: 'Duration format', 'zh-TW': '時間長度格式', 'zh-HK': '時間長度格式' },
    blurb: { en: 'Convert seconds to H:MM:SS and back.', 'zh-TW': '在秒數與 H:MM:SS 之間轉換。' },
  },
  {
    id: 'hex-text',
    category: 'dev',
    offline: true,
    keywords: ['hex', 'hexadecimal', 'encode', 'decode', 'text'],
    name: { en: 'Text ↔ hex', 'zh-TW': '文字 ↔ 十六進位', 'zh-HK': '文字 ↔ 十六進位' },
    blurb: { en: 'Convert text to hexadecimal and back.', 'zh-TW': '將文字轉為十六進位或還原。' },
  },
  {
    id: 'unicode-escape',
    category: 'dev',
    offline: true,
    keywords: ['unicode', 'escape', 'uXXXX', 'encode', 'decode'],
    name: { en: 'Unicode escape', 'zh-TW': 'Unicode 跳脫', 'zh-HK': 'Unicode 跳脫' },
    blurb: { en: 'Escape non-ASCII characters as \\uXXXX.', 'zh-TW': '將非 ASCII 字元跳脫為 \\uXXXX。' },
  },
  {
    id: 'reverse-words',
    category: 'text',
    offline: true,
    keywords: ['reverse', 'words', 'order', 'flip'],
    name: { en: 'Reverse words', 'zh-TW': '反轉詞序', 'zh-HK': '反轉詞序' },
    blurb: { en: 'Reverse the order of words in text.', 'zh-TW': '反轉文字中詞語的順序。' },
  },
  {
    id: 'tabs-spaces',
    category: 'dev',
    offline: true,
    keywords: ['tabs', 'spaces', 'indent', 'whitespace', 'format'],
    name: { en: 'Tabs ↔ spaces', 'zh-TW': 'Tab ↔ 空格', 'zh-HK': 'Tab ↔ 空格' },
    blurb: { en: 'Convert between tab characters and spaces.', 'zh-TW': '在 Tab 字元與空格之間轉換。' },
  },
  {
    id: 'rot47',
    category: 'text',
    offline: true,
    keywords: ['rot47', 'cipher', 'ascii', 'encode'],
    name: { en: 'ROT47', 'zh-TW': 'ROT47', 'zh-HK': 'ROT47' },
    blurb: { en: 'Encode or decode printable ASCII with ROT47.', 'zh-TW': '以 ROT47 編碼或解碼可列印 ASCII。' },
  },
  {
    id: 'hamming-distance',
    category: 'dev',
    offline: true,
    keywords: ['hamming', 'distance', 'compare', 'string', 'bits'],
    name: { en: 'Hamming distance', 'zh-TW': '漢明距離', 'zh-HK': '漢明距離' },
    blurb: { en: 'Count differing characters in equal-length strings.', 'zh-TW': '計算兩個等長字串中不同字元的數量。' },
  },
  {
    id: 'volume-convert',
    category: 'convert',
    offline: true,
    keywords: ['volume', 'litre', 'gallon', 'pint', 'cup'],
    name: { en: 'Volume converter', 'zh-TW': '體積換算', 'zh-HK': '體積換算' },
    blurb: { en: 'Convert litres, gallons, pints, and cups.', 'zh-TW': '換算公升、加侖、品脫與杯。' },
  },
  {
    id: 'angle-convert',
    category: 'convert',
    offline: true,
    keywords: ['angle', 'degree', 'radian', 'gradian'],
    name: { en: 'Angle converter', 'zh-TW': '角度換算', 'zh-HK': '角度換算' },
    blurb: { en: 'Convert degrees, radians, and gradians.', 'zh-TW': '換算度、弧度與百分度。' },
  },
  {
    id: 'char-frequency',
    category: 'text',
    offline: true,
    keywords: ['character', 'frequency', 'count', 'statistics'],
    name: { en: 'Character frequency', 'zh-TW': '字元頻率', 'zh-HK': '字元頻率' },
    blurb: { en: 'Count how often each character appears.', 'zh-TW': '統計各字元出現次數。' },
  },
  {
    id: 'line-prefix',
    category: 'text',
    offline: true,
    keywords: ['prefix', 'suffix', 'lines', 'affix', 'wrap'],
    name: { en: 'Line prefix / suffix', 'zh-TW': '行前後綴', 'zh-HK': '行前後綴' },
    blurb: { en: 'Add the same prefix and/or suffix to every line.', 'zh-TW': '為每一行加上相同的前綴或後綴。' },
  },
  {
    id: 'mass-convert',
    category: 'convert',
    offline: true,
    keywords: ['mass', 'weight', 'kg', 'lb', 'pound', 'ounce'],
    name: { en: 'Mass converter', 'zh-TW': '重量換算', 'zh-HK': '重量換算' },
    blurb: { en: 'Convert kilograms, pounds, ounces, and stone.', 'zh-TW': '換算公斤、磅、盎司與英石。' },
  },
  {
    id: 'temperature-convert',
    category: 'convert',
    offline: true,
    keywords: ['temperature', 'celsius', 'fahrenheit', 'kelvin'],
    name: { en: 'Temperature converter', 'zh-TW': '溫度換算', 'zh-HK': '溫度換算' },
    blurb: { en: 'Convert Celsius, Fahrenheit, and Kelvin.', 'zh-TW': '換算攝氏、華氏與開氏溫度。' },
  },
  {
    id: 'power-convert',
    category: 'convert',
    offline: true,
    keywords: ['power', 'watt', 'kilowatt', 'horsepower', 'hp'],
    name: { en: 'Power converter', 'zh-TW': '功率換算', 'zh-HK': '功率換算' },
    blurb: { en: 'Convert watts, kilowatts, megawatts, and horsepower.', 'zh-TW': '換算瓦、千瓦、兆瓦與馬力。' },
  },
  {
    id: 'frequency-convert',
    category: 'convert',
    offline: true,
    keywords: ['frequency', 'hertz', 'mhz', 'ghz', 'radio'],
    name: { en: 'Frequency converter', 'zh-TW': '頻率換算', 'zh-HK': '頻率換算' },
    blurb: { en: 'Convert Hz, kHz, MHz, and GHz.', 'zh-TW': '換算 Hz、kHz、MHz 與 GHz。' },
  },
  {
    id: 'truncate-text',
    category: 'text',
    offline: true,
    keywords: ['truncate', 'shorten', 'ellipsis', 'limit', 'length'],
    name: { en: 'Truncate text', 'zh-TW': '截斷文字', 'zh-HK': '截斷文字' },
    blurb: { en: 'Shorten text to a maximum length with an ellipsis.', 'zh-TW': '將文字縮短至最大長度並加上省略符號。' },
  },
  {
    id: 'pad-text',
    category: 'text',
    offline: true,
    keywords: ['pad', 'align', 'fill', 'width', 'format'],
    name: { en: 'Pad text', 'zh-TW': '補齊文字', 'zh-HK': '補齊文字' },
    blurb: { en: 'Pad text to a minimum width with a fill character.', 'zh-TW': '以填充字元將文字補齊至指定寬度。' },
  },
  {
    id: 'zero-width-clean',
    category: 'text',
    offline: true,
    keywords: ['zero-width', 'invisible', 'unicode', 'clean', 'zwsp'],
    name: { en: 'Remove zero-width chars', 'zh-TW': '移除零寬字元', 'zh-HK': '移除零寬字元' },
    blurb: { en: 'Strip invisible zero-width and formatting characters.', 'zh-TW': '移除不可見的零寬與格式字元。' },
  },
  {
    id: 'markdown-strip',
    category: 'dev',
    offline: true,
    keywords: ['markdown', 'strip', 'plain', 'text', 'md'],
    name: { en: 'Strip Markdown', 'zh-TW': '移除 Markdown', 'zh-HK': '移除 Markdown' },
    blurb: { en: 'Convert Markdown to plain text.', 'zh-TW': '將 Markdown 轉為純文字。' },
  },
  {
    id: 'atbash-cipher',
    category: 'text',
    offline: true,
    keywords: ['atbash', 'cipher', 'encode', 'decode', 'hebrew'],
    name: { en: 'Atbash cipher', 'zh-TW': 'Atbash 密碼', 'zh-HK': 'Atbash 密碼' },
    blurb: { en: 'Encode or decode letters with the Atbash cipher.', 'zh-TW': '以 Atbash 密碼編碼或解碼字母。' },
  },
  {
    id: 'base32-codec',
    category: 'dev',
    offline: true,
    keywords: ['base32', 'encode', 'decode', 'rfc4648', 'totp'],
    name: { en: 'Base32 encode / decode', 'zh-TW': 'Base32 編碼／解碼', 'zh-HK': 'Base32 編碼／解碼' },
    blurb: { en: 'Convert text to RFC 4648 base32 and back.', 'zh-TW': '將文字轉為 RFC 4648 Base32 或還原。' },
  },
  {
    id: 'length-convert',
    category: 'convert',
    offline: true,
    keywords: ['length', 'metre', 'mile', 'foot', 'distance'],
    name: { en: 'Length converter', 'zh-TW': '長度換算', 'zh-HK': '長度換算' },
    blurb: { en: 'Convert metres, kilometres, miles, feet, and more.', 'zh-TW': '換算公尺、公里、英里、英尺等。' },
  },
  {
    id: 'soundex',
    category: 'text',
    offline: true,
    keywords: ['soundex', 'phonetic', 'name', 'encode'],
    name: { en: 'Soundex', 'zh-TW': 'Soundex', 'zh-HK': 'Soundex' },
    blurb: { en: 'Compute the American Soundex phonetic code.', 'zh-TW': '計算美式 Soundex 語音編碼。' },
  },
  {
    id: 'jaccard-similarity',
    category: 'dev',
    offline: true,
    keywords: ['jaccard', 'similarity', 'compare', 'text', 'overlap'],
    name: { en: 'Jaccard similarity', 'zh-TW': 'Jaccard 相似度', 'zh-HK': 'Jaccard 相似度' },
    blurb: { en: 'Compare word overlap between two texts.', 'zh-TW': '比較兩段文字的詞彙重疊。' },
  },
  {
    id: 'quoted-printable',
    category: 'dev',
    offline: true,
    keywords: ['quoted-printable', 'qp', 'mime', 'email', 'encode'],
    name: { en: 'Quoted-printable', 'zh-TW': 'Quoted-printable', 'zh-HK': 'Quoted-printable' },
    blurb: { en: 'Encode or decode quoted-printable (RFC 2045).', 'zh-TW': '編碼或解碼 quoted-printable。' },
  },
  {
    id: 'extract-numbers',
    category: 'text',
    offline: true,
    keywords: ['extract', 'numbers', 'decimal', 'parse'],
    name: { en: 'Extract numbers', 'zh-TW': '擷取數字', 'zh-HK': '擷取數字' },
    blurb: { en: 'Pull integers and decimals from text.', 'zh-TW': '從文字中擷取整數與小數。' },
  },
  {
    id: 'extract-ipv4',
    category: 'dev',
    offline: true,
    keywords: ['ipv4', 'ip', 'address', 'extract', 'network'],
    name: { en: 'Extract IPv4', 'zh-TW': '擷取 IPv4', 'zh-HK': '擷取 IPv4' },
    blurb: { en: 'Find IPv4 addresses in text.', 'zh-TW': '從文字中找出 IPv4 位址。' },
  },
  {
    id: 'transpose-grid',
    category: 'dev',
    offline: true,
    keywords: ['transpose', 'grid', 'rows', 'columns', 'matrix'],
    name: { en: 'Transpose grid', 'zh-TW': '轉置網格', 'zh-HK': '轉置網格' },
    blurb: { en: 'Swap rows and columns in a character grid.', 'zh-TW': '將字元網格的行列互換。' },
  },
  {
    id: 'gcd-lcm',
    category: 'generator',
    offline: true,
    keywords: ['gcd', 'lcm', 'math', 'divisor', 'multiple'],
    name: { en: 'GCD & LCM', 'zh-TW': 'GCD 與 LCM', 'zh-HK': 'GCD 與 LCM' },
    blurb: { en: 'Greatest common divisor and least common multiple.', 'zh-TW': '最大公因數與最小公倍數。' },
  },
  {
    id: 'string-similarity',
    category: 'dev',
    offline: true,
    keywords: ['similarity', 'levenshtein', 'compare', 'percent', 'match'],
    name: { en: 'String similarity', 'zh-TW': '字串相似度', 'zh-HK': '字串相似度' },
    blurb: { en: 'Levenshtein-based similarity percentage.', 'zh-TW': '以 Levenshtein 計算相似百分比。' },
  },
  {
    id: 'mask-emails',
    category: 'text',
    offline: true,
    keywords: ['mask', 'email', 'redact', 'privacy', 'hide'],
    name: { en: 'Mask emails', 'zh-TW': '遮蔽 Email', 'zh-HK': '遮蔽 Email' },
    blurb: { en: 'Redact email addresses in text for sharing.', 'zh-TW': '遮蔽文字中的 Email 以便分享。' },
  },
  {
    id: 'hash',
    category: 'dev',
    offline: true,
    keywords: ['hash', 'sha', 'sha256', 'sha512', 'md5', 'sha1', 'checksum', 'digest', 'file'],
    name: {
      en: 'Hash (MD5 / SHA)',
      'zh-TW': '雜湊 (MD5 / SHA)',
      'zh-HK': '雜湊 (MD5 / SHA)',
      ja: 'ハッシュ (MD5 / SHA)',
      ko: '해시 (MD5 / SHA)',
      es: 'Hash (MD5 / SHA)',
      fr: 'Hachage (MD5 / SHA)',
      de: 'Hash (MD5 / SHA)',
    },
    blurb: {
      en: 'Compute MD5, SHA-1, SHA-256, and SHA-512 digests of text or files on-device.',
      'zh-TW': '在裝置上計算文字或檔案的 MD5、SHA-1、SHA-256、SHA-512 雜湊值。',
    },
  },
  {
    id: 'base64',
    category: 'dev',
    offline: true,
    keywords: ['base64', 'encode', 'decode', 'b64'],
    name: {
      en: 'Base64 encode / decode',
      'zh-TW': 'Base64 編碼／解碼',
      'zh-HK': 'Base64 編碼／解碼',
      ja: 'Base64 エンコード／デコード',
      ko: 'Base64 인코딩/디코딩',
      es: 'Codificar / decodificar Base64',
      fr: 'Encoder / décoder Base64',
      de: 'Base64 kodieren / dekodieren',
    },
    blurb: {
      en: 'Encode text to Base64 and decode it back, on-device.',
      'zh-TW': '在裝置上將文字編碼為 Base64 或解碼還原。',
    },
  },
  {
    id: 'url-encode',
    category: 'dev',
    offline: true,
    keywords: ['url', 'encode', 'decode', 'percent', 'uri'],
    name: {
      en: 'URL encode / decode',
      'zh-TW': 'URL 編碼／解碼',
      'zh-HK': 'URL 編碼／解碼',
      ja: 'URL エンコード／デコード',
      ko: 'URL 인코딩/디코딩',
      es: 'Codificar / decodificar URL',
      fr: 'Encoder / décoder une URL',
      de: 'URL kodieren / dekodieren',
    },
    blurb: {
      en: 'Percent-encode text for URLs and decode it back.',
      'zh-TW': '將文字進行網址百分比編碼或解碼。',
    },
  },
  {
    id: 'json-yaml',
    category: 'dev',
    offline: true,
    keywords: ['json', 'yaml', 'convert', 'config'],
    name: { en: 'JSON ↔ YAML' },
    blurb: {
      en: 'Convert between JSON and YAML.',
      'zh-TW': '在 JSON 與 YAML 之間轉換。',
    },
  },
  {
    id: 'regex-tester',
    category: 'dev',
    offline: true,
    keywords: ['regex', 'regexp', 'pattern', 'match', 'test'],
    name: {
      en: 'Regex tester',
      'zh-TW': '正規表達式測試',
      'zh-HK': '正則表達式測試',
      ja: '正規表現テスター',
      ko: '정규식 테스터',
      es: 'Probador de regex',
      fr: 'Testeur de regex',
      de: 'Regex-Tester',
    },
    blurb: {
      en: 'Test a regular expression against text and see every match.',
      'zh-TW': '以文字測試正規表達式並檢視所有比對結果。',
    },
  },
  {
    id: 'text-diff',
    category: 'text',
    offline: true,
    keywords: ['diff', 'compare', 'text', 'changes'],
    name: {
      en: 'Text diff',
      'zh-TW': '文字比對',
      'zh-HK': '文字比對',
      ja: 'テキスト差分',
      ko: '텍스트 비교',
      es: 'Comparar textos',
      fr: 'Comparaison de texte',
      de: 'Textvergleich',
    },
    blurb: {
      en: 'Compare two blocks of text line by line.',
      'zh-TW': '逐行比較兩段文字。',
    },
  },
  {
    id: 'fullwidth',
    category: 'text',
    offline: true,
    keywords: ['fullwidth', 'halfwidth', '全形', '半形', 'normalize'],
    name: {
      en: 'Full / half-width',
      'zh-TW': '全形／半形轉換',
      'zh-HK': '全形／半形轉換',
      ja: '全角・半角変換',
      ko: '전각/반각 변환',
      es: 'Ancho completo / medio',
      fr: 'Pleine / demi-chasse',
      de: 'Voll-/Halbbreite',
    },
    blurb: {
      en: 'Convert between full-width and half-width characters.',
      'zh-TW': '在全形與半形字元之間轉換。',
    },
  },
  {
    id: 'loan-calculator',
    category: 'finance',
    offline: true,
    keywords: ['loan', 'mortgage', 'payment', 'amortization', 'interest'],
    name: {
      en: 'Loan calculator',
      'zh-TW': '貸款計算機',
      'zh-HK': '貸款計算機',
      ja: 'ローン計算',
      ko: '대출 계산기',
      es: 'Calculadora de préstamos',
      fr: 'Calculatrice de prêt',
      de: 'Kreditrechner',
    },
    blurb: {
      en: 'Monthly payment and amortization schedule for a loan.',
      'zh-TW': '計算貸款每月還款與攤還表。',
    },
  },
  {
    id: 'bmi',
    category: 'calc',
    offline: true,
    keywords: ['bmi', 'body', 'mass', 'index', 'health', 'weight'],
    name: {
      en: 'BMI calculator',
      'zh-TW': 'BMI 計算機',
      'zh-HK': 'BMI 計算機',
      ja: 'BMI 計算',
      ko: 'BMI 계산기',
      es: 'Calculadora de IMC',
      fr: 'Calculatrice IMC',
      de: 'BMI-Rechner',
    },
    blurb: {
      en: 'Body mass index from height and weight.',
      'zh-TW': '依身高體重計算身體質量指數。',
    },
  },
  {
    id: 'date-diff',
    category: 'datetime',
    offline: true,
    keywords: ['date', 'days', 'difference', 'age', 'between'],
    name: {
      en: 'Date & age',
      'zh-TW': '日期與年齡',
      'zh-HK': '日期與年齡',
      ja: '日付・年齢計算',
      ko: '날짜·나이 계산',
      es: 'Fecha y edad',
      fr: 'Date et âge',
      de: 'Datum & Alter',
    },
    blurb: {
      en: 'Days between dates, add days, and exact age.',
      'zh-TW': '計算日期間隔、加減天數與實際年齡。',
    },
  },
  {
    id: 'qr-scan',
    category: 'generator',
    offline: true,
    keywords: ['qr', 'scan', 'decode', 'read', 'barcode'],
    name: {
      en: 'QR code scanner',
      'zh-TW': 'QR Code 掃描',
      'zh-HK': 'QR Code 掃描',
      ja: 'QR コード読み取り',
      ko: 'QR 코드 스캐너',
      es: 'Escáner de códigos QR',
      fr: 'Scanner de QR code',
      de: 'QR-Code-Scanner',
    },
    blurb: {
      en: 'Read the text inside a QR code image.',
      'zh-TW': '讀取 QR Code 影像中的文字。',
    },
  },
  {
    id: 'pdf-split',
    category: 'pdf',
    offline: true,
    keywords: ['pdf', 'split', 'pages', 'separate', 'extract'],
    name: {
      en: 'Split PDF',
      'zh-TW': '分割 PDF',
      'zh-HK': '分割 PDF',
      ja: 'PDF を分割',
      ko: 'PDF 분할',
      es: 'Dividir PDF',
      fr: 'Diviser un PDF',
      de: 'PDF teilen',
    },
    blurb: {
      en: 'Split a PDF into one file per page.',
      'zh-TW': '將 PDF 依頁拆成多個檔案。',
    },
  },
  {
    id: 'pdf-compress',
    category: 'pdf',
    offline: true,
    keywords: ['pdf', 'compress', 'shrink', 'reduce', 'size', 'optimize'],
    name: {
      en: 'Compress PDF',
      'zh-TW': '壓縮 PDF',
      'zh-HK': '壓縮 PDF',
      ja: 'PDF を圧縮',
      ko: 'PDF 압축',
      es: 'Comprimir PDF',
      fr: 'Compresser un PDF',
      de: 'PDF komprimieren',
    },
    blurb: {
      en: 'Reduce a PDF file size on your device. Nothing is uploaded.',
      'zh-TW': '在裝置上縮小 PDF 檔案大小，完全不上傳。',
    },
  },
  {
    id: 'zip-create',
    category: 'file',
    offline: true,
    keywords: ['zip', 'archive', 'compress', 'bundle', 'files'],
    name: {
      en: 'Create ZIP',
      'zh-TW': '建立 ZIP',
      'zh-HK': '建立 ZIP',
      ja: 'ZIP を作成',
      ko: 'ZIP 만들기',
      es: 'Crear ZIP',
      fr: 'Créer un ZIP',
      de: 'ZIP erstellen',
    },
    blurb: {
      en: 'Bundle several files into one ZIP archive, on your device.',
      'zh-TW': '在裝置上將多個檔案打包成一個 ZIP 壓縮檔。',
    },
  },
  {
    id: 'zip-extract',
    category: 'file',
    offline: true,
    keywords: ['zip', 'extract', 'unzip', 'archive', 'open'],
    name: {
      en: 'Extract ZIP',
      'zh-TW': '解壓 ZIP',
      'zh-HK': '解壓 ZIP',
      ja: 'ZIP を展開',
      ko: 'ZIP 압축 풀기',
      es: 'Extraer ZIP',
      fr: 'Extraire un ZIP',
      de: 'ZIP entpacken',
    },
    blurb: {
      en: 'Open a ZIP archive and download the files inside.',
      'zh-TW': '開啟 ZIP 壓縮檔並下載其中的檔案。',
    },
  },
  {
    id: 'heic-convert',
    category: 'image',
    offline: true,
    keywords: ['heic', 'heif', 'jpg', 'jpeg', 'convert', 'iphone', 'photo'],
    name: { en: 'HEIC → JPG', 'zh-TW': 'HEIC → JPG' },
    blurb: {
      en: 'Convert iPhone HEIC/HEIF photos to JPG on your device.',
      'zh-TW': '在裝置上將 iPhone 的 HEIC／HEIF 相片轉為 JPG。',
    },
  },
  {
    id: 'discount',
    category: 'calc',
    offline: true,
    keywords: ['discount', 'sale', 'price', 'percent', 'off', 'savings'],
    name: {
      en: 'Discount calculator',
      'zh-TW': '折扣計算機',
      'zh-HK': '折扣計算機',
      ja: '割引計算',
      ko: '할인 계산기',
      es: 'Calculadora de descuentos',
      fr: 'Calculatrice de remise',
      de: 'Rabattrechner',
    },
    blurb: {
      en: 'Work out a sale price and how much you save.',
      'zh-TW': '計算折扣後價格與省下的金額。',
    },
  },
  {
    id: 'savings',
    category: 'finance',
    offline: true,
    keywords: ['interest', 'savings', 'compound', 'simple', 'investment'],
    name: {
      en: 'Savings & interest',
      'zh-TW': '儲蓄與利息',
      'zh-HK': '儲蓄與利息',
      ja: '貯蓄・利息計算',
      ko: '저축·이자 계산',
      es: 'Ahorro e interés',
      fr: 'Épargne et intérêts',
      de: 'Sparen & Zinsen',
    },
    blurb: {
      en: 'Simple and compound interest on a deposit over time.',
      'zh-TW': '計算存款隨時間累積的單利與複利。',
    },
  },
  {
    id: 'cooking-convert',
    category: 'convert',
    offline: true,
    keywords: ['cooking', 'recipe', 'cup', 'gram', 'ml', 'baking', 'kitchen'],
    name: {
      en: 'Cooking converter',
      'zh-TW': '烹飪單位換算',
      'zh-HK': '烹飪單位換算',
      ja: '料理の単位変換',
      ko: '요리 단위 변환',
      es: 'Conversor de cocina',
      fr: 'Convertisseur de cuisine',
      de: 'Küchen-Umrechner',
    },
    blurb: {
      en: 'Convert cups, grams and millilitres for common ingredients.',
      'zh-TW': '換算常見食材的杯、公克與毫升。',
    },
  },
  {
    id: 'password',
    category: 'generator',
    offline: true,
    keywords: ['password', 'random', 'secure', 'generate', 'passphrase'],
    name: {
      en: 'Password generator',
      'zh-TW': '密碼產生器',
      'zh-HK': '密碼產生器',
      ja: 'パスワード生成',
      ko: '비밀번호 생성기',
      es: 'Generador de contraseñas',
      fr: 'Générateur de mots de passe',
      de: 'Passwort-Generator',
    },
    blurb: {
      en: 'Generate strong random passwords in your browser.',
      'zh-TW': '在瀏覽器中產生高強度隨機密碼。',
    },
  },
  {
    id: 'uuid',
    category: 'generator',
    offline: true,
    keywords: ['uuid', 'guid', 'id', 'random', 'v4'],
    name: {
      en: 'UUID generator',
      'zh-TW': 'UUID 產生器',
      'zh-HK': 'UUID 產生器',
      ja: 'UUID 生成',
      ko: 'UUID 생성기',
      es: 'Generador de UUID',
      fr: 'Générateur d’UUID',
      de: 'UUID-Generator',
    },
    blurb: {
      en: 'Generate random version-4 UUIDs on your device.',
      'zh-TW': '在裝置上產生隨機的第 4 版 UUID。',
    },
  },
  {
    id: 'jwt-decode',
    category: 'dev',
    offline: true,
    keywords: ['jwt', 'token', 'decode', 'json', 'web', 'auth'],
    name: {
      en: 'JWT decoder',
      'zh-TW': 'JWT 解碼',
      'zh-HK': 'JWT 解碼',
      ja: 'JWT デコーダー',
      ko: 'JWT 디코더',
      es: 'Decodificador JWT',
      fr: 'Décodeur JWT',
      de: 'JWT-Decoder',
    },
    blurb: {
      en: "Decode a JWT's header and payload (no signature check).",
      'zh-TW': '解碼 JWT 的標頭與內容（不驗證簽章）。',
    },
  },
  {
    id: 'base-convert',
    category: 'dev',
    offline: true,
    keywords: ['base', 'binary', 'hex', 'octal', 'decimal', 'radix', 'number'],
    name: {
      en: 'Number base converter',
      'zh-TW': '進位轉換',
      'zh-HK': '進位轉換',
      ja: '基数変換',
      ko: '진법 변환',
      es: 'Conversor de bases',
      fr: 'Convertisseur de base',
      de: 'Zahlensystem-Umrechner',
    },
    blurb: {
      en: 'Convert integers between binary, octal, decimal and hex.',
      'zh-TW': '在二、八、十、十六進位之間轉換整數。',
    },
  },
  {
    id: 'color-convert',
    category: 'dev',
    offline: true,
    keywords: ['color', 'colour', 'hex', 'rgb', 'hsl', 'convert'],
    name: {
      en: 'Color converter',
      'zh-TW': '色彩轉換',
      'zh-HK': '色彩轉換',
      ja: 'カラー変換',
      ko: '색상 변환',
      es: 'Conversor de color',
      fr: 'Convertisseur de couleur',
      de: 'Farb-Umrechner',
    },
    blurb: {
      en: 'Convert a color between HEX, RGB and HSL.',
      'zh-TW': '在 HEX、RGB、HSL 之間轉換色彩。',
    },
  },
  {
    id: 'cron',
    category: 'dev',
    offline: true,
    keywords: ['cron', 'crontab', 'schedule', 'explain', 'expression'],
    name: {
      en: 'Cron explainer',
      'zh-TW': 'Cron 說明',
      'zh-HK': 'Cron 說明',
      ja: 'Cron 解説',
      ko: 'Cron 설명기',
      es: 'Explicador de cron',
      fr: 'Explicateur cron',
      de: 'Cron-Erklärer',
    },
    blurb: {
      en: 'Turn a 5-field cron expression into plain language.',
      'zh-TW': '將 5 欄位的 cron 表達式轉為白話說明。',
    },
  },
  {
    id: 'image-resize',
    category: 'image',
    offline: true,
    keywords: ['image', 'resize', 'scale', 'dimensions', 'pixels'],
    name: {
      en: 'Resize image',
      'zh-TW': '影像尺寸調整',
      'zh-HK': '圖片尺寸調整',
      ja: '画像をリサイズ',
      ko: '이미지 크기 조정',
      es: 'Redimensionar imagen',
      fr: 'Redimensionner une image',
      de: 'Bild skalieren',
    },
    blurb: {
      en: 'Resize an image to exact pixels or fit within a box.',
      'zh-TW': '將影像調整為指定像素或縮放至框內。',
    },
  },
  {
    id: 'image-crop',
    category: 'image',
    offline: true,
    keywords: ['image', 'crop', 'cut', 'trim', 'rectangle'],
    name: {
      en: 'Crop image',
      'zh-TW': '影像裁切',
      'zh-HK': '圖片裁切',
      ja: '画像を切り抜き',
      ko: '이미지 자르기',
      es: 'Recortar imagen',
      fr: 'Rogner une image',
      de: 'Bild zuschneiden',
    },
    blurb: {
      en: 'Cut a rectangle out of an image by pixel coordinates.',
      'zh-TW': '依像素座標從影像裁下一塊矩形。',
    },
  },
  {
    id: 'exif-strip',
    category: 'image',
    offline: true,
    keywords: ['exif', 'metadata', 'gps', 'strip', 'privacy', 'remove'],
    name: {
      en: 'Strip image metadata',
      'zh-TW': '移除影像中繼資料',
      'zh-HK': '移除圖片中繼資料',
      ja: '画像メタデータを削除',
      ko: '이미지 메타데이터 제거',
      es: 'Quitar metadatos de imagen',
      fr: 'Supprimer les métadonnées',
      de: 'Bild-Metadaten entfernen',
    },
    blurb: {
      en: 'Remove EXIF/GPS metadata by re-encoding the image.',
      'zh-TW': '重新編碼影像以移除 EXIF／GPS 中繼資料。',
    },
  },
  {
    id: 'favicon',
    category: 'generator',
    offline: true,
    keywords: ['favicon', 'icon', 'app icon', 'png', 'website'],
    name: {
      en: 'Favicon generator',
      'zh-TW': 'Favicon 產生器',
      'zh-HK': 'Favicon 產生器',
      ja: 'Favicon 生成',
      ko: '파비콘 생성기',
      es: 'Generador de favicon',
      fr: 'Générateur de favicon',
      de: 'Favicon-Generator',
    },
    blurb: {
      en: 'Turn an image into a set of favicon / app-icon PNGs.',
      'zh-TW': '將圖片轉成一組 favicon／App 圖示 PNG。',
    },
  },
  {
    id: 'pdf-rotate',
    category: 'pdf',
    offline: true,
    keywords: ['pdf', 'rotate', 'turn', 'orientation', 'landscape'],
    name: {
      en: 'Rotate PDF',
      'zh-TW': '旋轉 PDF',
      'zh-HK': '旋轉 PDF',
      ja: 'PDF を回転',
      ko: 'PDF 회전',
      es: 'Rotar PDF',
      fr: 'Pivoter un PDF',
      de: 'PDF drehen',
    },
    blurb: {
      en: 'Rotate every page of a PDF on your device.',
      'zh-TW': '在裝置上旋轉 PDF 的每一頁。',
    },
  },
  {
    id: 'pdf-watermark',
    category: 'pdf',
    offline: true,
    keywords: ['pdf', 'watermark', 'stamp', 'confidential', 'text'],
    name: {
      en: 'Watermark PDF',
      'zh-TW': 'PDF 浮水印',
      'zh-HK': 'PDF 浮水印',
      ja: 'PDF に透かし',
      ko: 'PDF 워터마크',
      es: 'Marca de agua en PDF',
      fr: 'Filigrane PDF',
      de: 'PDF-Wasserzeichen',
    },
    blurb: {
      en: 'Stamp a diagonal text watermark across every page.',
      'zh-TW': '為 PDF 每一頁加上斜向文字浮水印。',
    },
  },
  {
    id: 'pdf-organize',
    category: 'pdf',
    offline: true,
    keywords: ['pdf', 'reorder', 'delete', 'pages', 'organize', 'rearrange'],
    name: {
      en: 'Organize PDF pages',
      'zh-TW': '重整 PDF 頁面',
      'zh-HK': '重整 PDF 頁面',
      ja: 'PDF ページを整理',
      ko: 'PDF 페이지 정리',
      es: 'Organizar páginas PDF',
      fr: 'Organiser les pages PDF',
      de: 'PDF-Seiten organisieren',
    },
    blurb: {
      en: 'Reorder or delete pages by listing the ones to keep.',
      'zh-TW': '依序列出要保留的頁面來重排或刪除頁面。',
    },
  },
  {
    id: 'pdf-page-numbers',
    category: 'pdf',
    offline: true,
    keywords: ['pdf', 'page', 'numbers', 'pagination', 'footer'],
    name: {
      en: 'Add page numbers',
      'zh-TW': '加入頁碼',
      'zh-HK': '加入頁碼',
      ja: 'ページ番号を追加',
      ko: '페이지 번호 추가',
      es: 'Agregar números de página',
      fr: 'Ajouter des numéros de page',
      de: 'Seitenzahlen hinzufügen',
    },
    blurb: {
      en: 'Stamp "n / total" page numbers on each page.',
      'zh-TW': '於每頁加上「n / 總頁數」頁碼。',
    },
  },
  {
    id: 'scientific',
    category: 'calc',
    offline: true,
    keywords: ['scientific', 'calculator', 'math', 'sin', 'cos', 'sqrt', 'expression'],
    name: {
      en: 'Scientific calculator',
      'zh-TW': '科學計算機',
      'zh-HK': '科學計算機',
      ja: '関数電卓',
      ko: '공학용 계산기',
      es: 'Calculadora científica',
      fr: 'Calculatrice scientifique',
      de: 'Wissenschaftlicher Rechner',
    },
    blurb: {
      en: 'Evaluate math expressions with functions and constants.',
      'zh-TW': '計算含函數與常數的數學式。',
    },
  },
  {
    id: 'timezone',
    category: 'datetime',
    offline: true,
    keywords: ['timezone', 'time zone', 'meeting', 'world clock', 'planner', 'convert'],
    name: {
      en: 'Time-zone planner',
      'zh-TW': '時區規劃',
      'zh-HK': '時區規劃',
      ja: 'タイムゾーン計画',
      ko: '시간대 플래너',
      es: 'Planificador de zonas horarias',
      fr: 'Planificateur de fuseaux horaires',
      de: 'Zeitzonen-Planer',
    },
    blurb: {
      en: 'See one moment across major cities and time zones.',
      'zh-TW': '查看同一時刻在世界主要城市的時間。',
    },
  },
  {
    id: 'checksum-validate',
    category: 'id',
    offline: true,
    keywords: ['luhn', 'credit card', 'iban', 'aba', 'routing', 'validate', 'checksum'],
    name: {
      en: 'Checksum validator',
      'zh-TW': '檢查碼驗證',
      'zh-HK': '檢查碼驗證',
      ja: 'チェックサム検証',
      ko: '체크섬 검증',
      es: 'Validador de suma de control',
      fr: 'Validateur de somme de contrôle',
      de: 'Prüfsummen-Validator',
    },
    blurb: {
      en: 'Validate a credit-card (Luhn), IBAN or ABA routing number.',
      'zh-TW': '驗證信用卡號（Luhn）、IBAN 或 ABA 代碼。',
    },
  },
  {
    id: 'sales-tax',
    category: 'finance',
    offline: true,
    keywords: ['sales tax', 'vat', 'gst', 'tax', 'net', 'gross'],
    name: {
      en: 'Sales tax / VAT / GST',
      'zh-TW': '銷售稅／VAT',
      'zh-HK': '銷售稅／VAT',
      ja: '消費税・VAT・GST',
      ko: '판매세 / VAT / GST',
      es: 'Impuesto sobre ventas / IVA',
      fr: 'Taxe de vente / TVA',
      de: 'Umsatzsteuer / MwSt.',
    },
    blurb: {
      en: 'Add or extract sales tax (VAT/GST) on an amount.',
      'zh-TW': '在金額上計算或拆分銷售稅（VAT／GST）。',
    },
  },
  {
    id: 'business-days',
    category: 'datetime',
    offline: true,
    keywords: ['business days', 'working days', 'weekdays', 'between', 'dates'],
    name: {
      en: 'Business days',
      'zh-TW': '工作日計算',
      'zh-HK': '工作日計算',
      ja: '営業日計算',
      ko: '영업일 계산',
      es: 'Días hábiles',
      fr: 'Jours ouvrés',
      de: 'Werktage',
    },
    blurb: {
      en: 'Count working days (weekends excluded) between two dates.',
      'zh-TW': '計算兩日期間的工作日（不含週末）。',
    },
  },
  {
    id: 'zodiac',
    category: 'daily',
    offline: true,
    keywords: ['zodiac', 'chinese', 'animal', 'birth year', '生肖'],
    name: {
      en: 'Chinese zodiac',
      'zh-TW': '生肖',
      'zh-HK': '生肖',
      ja: '干支・十二支',
      ko: '띠 (십이지)',
      es: 'Zodíaco chino',
      fr: 'Zodiaque chinois',
      de: 'Chinesisches Tierkreiszeichen',
    },
    blurb: {
      en: 'Find the Chinese zodiac animal for a birth year.',
      'zh-TW': '依出生年份查詢生肖。',
    },
  },
  {
    id: 'era-convert',
    category: 'datetime',
    offline: true,
    keywords: ['era', 'roc', 'minguo', '民國', 'japanese', '和曆', 'reiwa'],
    name: {
      en: 'Era converter',
      'zh-TW': '紀年轉換',
      'zh-HK': '紀年轉換',
      ja: '和暦・元号変換',
      ko: '연호 변환',
      es: 'Conversor de eras',
      fr: 'Convertisseur d’ères',
      de: 'Ära-Umrechner',
    },
    blurb: {
      en: 'Convert a Gregorian date to ROC (Minguo) and Japanese era.',
      'zh-TW': '將西元日期轉換為民國年與日本和曆。',
    },
  },
  {
    id: 'cjk-convert',
    category: 'text',
    offline: true,
    keywords: ['chinese', 'simplified', 'traditional', '繁簡', '简繁', 'opencc', 'cjk'],
    name: {
      en: 'Chinese converter',
      'zh-TW': '繁簡轉換',
      'zh-HK': '繁簡轉換',
      ja: '簡体・繁体変換',
      ko: '중국어 간체·번체 변환',
      es: 'Conversor de chino',
      fr: 'Convertisseur chinois',
      de: 'Chinesisch-Umwandler',
    },
    blurb: {
      en: 'Convert between Simplified and Traditional Chinese (Taiwan idioms).',
      'zh-TW': '在簡體與繁體中文之間轉換（含台灣用語）。',
    },
  },
  {
    id: 'html-entities',
    category: 'dev',
    offline: true,
    keywords: ['html', 'entities', 'escape', 'encode', 'decode', 'ampersand'],
    name: {
      en: 'HTML entities',
      'zh-TW': 'HTML 實體',
      'zh-HK': 'HTML 實體',
      ja: 'HTML エンティティ',
      ko: 'HTML 엔티티',
      es: 'Entidades HTML',
      fr: 'Entités HTML',
      de: 'HTML-Entitäten',
    },
    blurb: {
      en: 'Escape text to HTML entities or decode them back.',
      'zh-TW': '將文字轉為 HTML 實體或解碼還原。',
    },
  },
  {
    id: 'lunar-convert',
    category: 'datetime',
    offline: true,
    keywords: ['lunar', 'chinese calendar', '農曆', '农历', 'ganzhi', 'zodiac'],
    name: {
      en: 'Lunar calendar',
      'zh-TW': '農曆換算',
      'zh-HK': '農曆換算',
      ja: '旧暦変換',
      ko: '음력 변환',
      es: 'Calendario lunar',
      fr: 'Calendrier lunaire',
      de: 'Mondkalender',
    },
    blurb: {
      en: 'Convert a Gregorian date to the Chinese lunar calendar.',
      'zh-TW': '將西元日期轉換為農曆。',
    },
  },
  {
    id: 'rokuyo',
    category: 'daily',
    offline: true,
    keywords: ['rokuyo', '六曜', 'taian', 'butsumetsu', 'japanese', 'calendar'],
    name: {
      en: 'Rokuyō (六曜)',
      'zh-TW': '六曜',
      'zh-HK': '六曜',
      ja: '六曜',
      ko: '로쿠요 (六曜)',
      es: 'Rokuyō (六曜)',
      fr: 'Rokuyō (六曜)',
      de: 'Rokuyō (六曜)',
    },
    blurb: {
      en: 'The Japanese six-day calendar label for a date.',
      'zh-TW': '查詢日本六曜對應日期。',
    },
  },
  {
    id: 'solar-terms',
    category: 'datetime',
    offline: true,
    keywords: ['solar terms', '節氣', '节气', '二十四節氣', 'jieqi', 'sekki'],
    name: {
      en: 'Solar terms (節氣)',
      'zh-TW': '二十四節氣',
      'zh-HK': '二十四節氣',
      ja: '二十四節気',
      ko: '24절기',
      es: 'Términos solares (節氣)',
      fr: 'Termes solaires (節氣)',
      de: 'Solarterme (節氣)',
    },
    blurb: {
      en: 'The 24 solar terms for a year, with dates.',
      'zh-TW': '查詢指定年份的二十四節氣與日期。',
    },
  },
  {
    id: 'xml-json',
    category: 'dev',
    offline: true,
    keywords: ['xml', 'json', 'convert', 'parse', 'data'],
    name: { en: 'XML ↔ JSON' },
    blurb: {
      en: 'Convert between XML and JSON.',
      'zh-TW': '在 XML 與 JSON 之間轉換。',
    },
  },
  {
    id: 'csv-excel',
    category: 'convert',
    offline: true,
    keywords: ['csv', 'excel', 'xlsx', 'spreadsheet', 'convert', 'sheet'],
    name: { en: 'CSV ↔ Excel', 'zh-TW': 'CSV ↔ Excel' },
    blurb: {
      en: 'Convert CSV to an .xlsx workbook and back.',
      'zh-TW': '將 CSV 轉為 .xlsx 活頁簿或反向轉換。',
    },
  },
  {
    id: 'barcode',
    category: 'generator',
    offline: true,
    keywords: ['barcode', 'code128', 'ean', 'upc', 'datamatrix', 'pdf417'],
    name: {
      en: 'Barcode generator',
      'zh-TW': '條碼產生器',
      'zh-HK': '條碼產生器',
      ja: 'バーコード生成',
      ko: '바코드 생성기',
      es: 'Generador de códigos de barras',
      fr: 'Générateur de code-barres',
      de: 'Barcode-Generator',
    },
    blurb: {
      en: 'Generate barcodes and 2D codes as SVG.',
      'zh-TW': '產生條碼與 2D 碼並輸出 SVG。',
    },
  },
  {
    id: 'ocr',
    category: 'image',
    offline: false,
    keywords: ['ocr', 'text', 'recognize', 'scan', 'extract', 'tesseract'],
    name: {
      en: 'Image to text (OCR)',
      'zh-TW': '圖片轉文字（OCR）',
      'zh-HK': '圖片轉文字（OCR）',
      ja: '画像から文字（OCR）',
      ko: '이미지 문자 인식 (OCR)',
      es: 'Imagen a texto (OCR)',
      fr: 'Image en texte (OCR)',
      de: 'Bild zu Text (OCR)',
    },
    blurb: {
      en: 'Extract text from an image (model downloads on first use).',
      'zh-TW': '從圖片擷取文字（模型於首次使用時下載）。',
    },
  },
  {
    id: 'bg-remove',
    category: 'image',
    offline: false,
    keywords: ['background', 'remove', 'cutout', 'transparent', 'png'],
    name: {
      en: 'Remove background',
      'zh-TW': '去背',
      'zh-HK': '去背',
      ja: '背景を削除',
      ko: '배경 제거',
      es: 'Quitar fondo',
      fr: 'Supprimer l’arrière-plan',
      de: 'Hintergrund entfernen',
    },
    blurb: {
      en: 'Cut out a photo background to a transparent PNG (model downloads on first use).',
      'zh-TW': '去除相片背景並輸出透明 PNG（模型於首次使用時下載）。',
    },
  },
  {
    id: 'currency-convert',
    category: 'convert',
    offline: true,
    keywords: ['currency', 'exchange', 'rate', 'forex', 'fx', 'convert', 'money'],
    name: {
      en: 'Currency converter',
      'zh-TW': '匯率換算',
      'zh-HK': '匯率換算',
      ja: '通貨換算',
      ko: '환율 변환',
      es: 'Conversor de divisas',
      fr: 'Convertisseur de devises',
      de: 'Währungsrechner',
    },
    blurb: {
      en: 'Convert amounts between currencies using a rate you provide.',
      'zh-TW': '以您提供的匯率換算不同幣別金額。',
    },
  },
  {
    id: 'json-format',
    category: 'dev',
    offline: true,
    keywords: ['json', 'format', 'pretty', 'minify', 'prettify', 'validate', 'indent'],
    name: {
      en: 'JSON formatter',
      'zh-TW': 'JSON 格式化',
      'zh-HK': 'JSON 格式化',
      ja: 'JSON 整形',
      ko: 'JSON 포맷터',
      es: 'Formateador JSON',
      fr: 'Formateur JSON',
      de: 'JSON-Formatierer',
    },
    blurb: {
      en: 'Validate, pretty-print, or minify JSON on your device.',
      'zh-TW': '在裝置上驗證、美化或壓縮 JSON。',
    },
  },
  {
    id: 'paycheck-calc',
    category: 'finance',
    offline: true,
    keywords: ['paycheck', 'salary', 'net', 'gross', 'take home', 'deductions', 'payroll'],
    name: {
      en: 'Paycheck calculator',
      'zh-TW': '薪資試算',
      'zh-HK': '薪資試算',
      ja: '手取り計算',
      ko: '급여 계산기',
      es: 'Calculadora de nómina',
      fr: 'Calculatrice de paie',
      de: 'Gehaltsrechner',
    },
    blurb: {
      en: 'Estimate take-home pay or find the gross needed for a target net.',
      'zh-TW': '估算實領薪資或由目標實領反推税前薪資。',
    },
  },
  {
    id: 'video-convert',
    category: 'convert',
    offline: false,
    keywords: ['video', 'convert', 'transcode', 'mp4', 'webm', 'ffmpeg'],
    name: {
      en: 'Convert video',
      'zh-TW': '影片轉檔',
      'zh-HK': '影片轉檔',
      ja: '動画変換',
      ko: '동영상 변환',
      es: 'Convertir video',
      fr: 'Convertir une vidéo',
      de: 'Video umwandeln',
    },
    blurb: {
      en: 'Transcode a video file on your device with ffmpeg.wasm.',
      'zh-TW': '使用 ffmpeg.wasm 在裝置上轉換影片。',
    },
  },
  {
    id: 'audio-extract',
    category: 'convert',
    offline: false,
    keywords: ['audio', 'mp3', 'extract', 'video', 'mp4', 'ffmpeg', 'sound'],
    name: { en: 'Extract audio', 'zh-TW': '擷取音訊', 'zh-HK': '擷取音訊' },
    blurb: {
      en: 'Strip the video track and save MP3 or M4A audio from a video file.',
      'zh-TW': '從影片擷取 MP3 或 M4A 音訊。',
    },
  },
  {
    id: 'reminder-planner',
    category: 'daily',
    offline: true,
    keywords: ['reminder', 'recurrence', 'schedule', 'repeat', 'notify', 'calendar'],
    name: {
      en: 'Reminder planner',
      'zh-TW': '提醒規劃',
      'zh-HK': '提醒規劃',
      ja: 'リマインダー計画',
      ko: '알림 플래너',
      es: 'Planificador de recordatorios',
      fr: 'Planificateur de rappels',
      de: 'Erinnerungsplaner',
    },
    blurb: {
      en: 'Preview upcoming reminder dates from a recurrence rule.',
      'zh-TW': '依重複規則預覽 upcoming 提醒日期。',
    },
  },
  {
    id: 'images-to-pdf',
    category: 'pdf',
    offline: true,
    keywords: ['image', 'jpg', 'png', 'pdf', 'combine', 'photos'],
    name: { en: 'Images to PDF', 'zh-TW': '圖片轉 PDF', 'zh-HK': '圖片轉 PDF' },
    blurb: {
      en: 'Combine JPEG or PNG images into one PDF, one page per image.',
      'zh-TW': '將 JPEG 或 PNG 合併為 PDF，每張圖片一頁。',
    },
  },
  {
    id: 'pdf-to-images',
    category: 'pdf',
    offline: true,
    keywords: ['pdf', 'image', 'png', 'jpeg', 'rasterize', 'pages'],
    name: { en: 'PDF to images', 'zh-TW': 'PDF 轉圖片', 'zh-HK': 'PDF 轉圖片' },
    blurb: {
      en: 'Rasterize each PDF page to PNG or JPEG on your device.',
      'zh-TW': '將 PDF 每一頁轉為 PNG 或 JPEG。',
    },
  },
  {
    id: 'docx-to-pdf',
    category: 'convert',
    offline: false,
    keywords: ['docx', 'word', 'pdf', 'document', 'convert', 'office'],
    name: { en: 'Word to PDF', 'zh-TW': 'Word 轉 PDF', 'zh-HK': 'Word 轉 PDF' },
    blurb: {
      en: 'Convert a .docx file to PDF via the backend conversion worker.',
      'zh-TW': '透過後端 worker 將 .docx 轉為 PDF。',
    },
  },
  {
    id: 'pptx-to-pdf',
    category: 'convert',
    offline: false,
    keywords: ['pptx', 'powerpoint', 'pdf', 'presentation', 'convert', 'office'],
    name: { en: 'PowerPoint to PDF', 'zh-TW': 'PowerPoint 轉 PDF', 'zh-HK': 'PowerPoint 轉 PDF' },
    blurb: {
      en: 'Convert a .pptx file to PDF via the backend conversion worker.',
      'zh-TW': '透過後端 worker 將 .pptx 轉為 PDF。',
    },
  },
  {
    id: 'pdf-to-word',
    category: 'convert',
    offline: false,
    keywords: ['pdf', 'docx', 'word', 'document', 'convert', 'office'],
    name: { en: 'PDF to Word', 'zh-TW': 'PDF 轉 Word', 'zh-HK': 'PDF 轉 Word' },
    blurb: {
      en: 'Convert a PDF to an editable .docx file via the backend worker.',
      'zh-TW': '透過後端 worker 將 PDF 轉為可編輯的 .docx。',
    },
  },
  {
    id: 'ca-sin',
    category: 'id',
    offline: true,
    keywords: ['canada', 'sin', 'social insurance', 'luhn', 'validate'],
    name: { en: 'Canadian SIN', 'zh-TW': '加拿大 SIN' },
    blurb: {
      en: 'Validate a Canadian Social Insurance Number (Luhn check).',
      'zh-TW': '驗證加拿大社會保險號碼（Luhn）。',
    },
  },
  {
    id: 'au-tfn',
    category: 'id',
    offline: true,
    keywords: ['australia', 'tfn', 'tax file number', 'validate'],
    name: { en: 'Australian TFN', 'zh-TW': '澳洲 TFN' },
    blurb: {
      en: 'Validate an Australian Tax File Number (mod-11 check).',
      'zh-TW': '驗證澳洲稅務檔案號碼（mod-11）。',
    },
  },

  // --- Market packs (Phase 3) — shown when the matching region is selected. ---
  {
    id: 'tw-invoice',
    category: 'finance',
    offline: true,
    markets: ['tw'],
    keywords: ['taiwan', 'invoice', 'lottery', '統一發票', '對獎', '發票', '中獎', 'receipt'],
    name: {
      en: 'Taiwan invoice lottery',
      'zh-TW': '統一發票對獎',
      'zh-HK': '台灣統一發票對獎',
      ja: '台湾統一発票くじ',
      ko: '대만 통일발표 복권',
      es: 'Lotería de facturas (Taiwán)',
      fr: 'Loterie des factures (Taïwan)',
      de: 'Rechnungslotterie (Taiwan)',
    },
    blurb: {
      en: 'Check a 統一發票 receipt against the period’s winning numbers, on-device.',
      'zh-TW': '輸入本期中獎號碼即可對獎，全程於裝置上運算。',
    },
  },
  {
    id: 'tw-national-id',
    category: 'id',
    offline: true,
    markets: ['tw'],
    keywords: ['taiwan', 'national id', '身分證', '台灣', 'validate'],
    name: {
      en: 'Taiwan National ID',
      'zh-TW': '身分證字號驗證',
      'zh-HK': '台灣身分證驗證',
      ja: '台湾国民身分証番号',
      ko: '대만 주민등록번호',
      es: 'DNI de Taiwán',
      fr: 'Carte d’identité taïwanaise',
      de: 'Taiwan-Personalausweis',
    },
    blurb: {
      en: 'Validate or generate a Taiwan National ID number.',
      'zh-TW': '驗證或產生中華民國身分證字號。',
    },
  },
  {
    id: 'tw-ubn',
    category: 'id',
    offline: true,
    markets: ['tw'],
    keywords: ['taiwan', 'business', '統編', '統一編號', 'ubn', 'validate'],
    name: {
      en: 'Taiwan business number',
      'zh-TW': '統一編號驗證',
      'zh-HK': '台灣統一編號',
      ja: '台湾統一番号',
      ko: '대만 사업자번호',
      es: 'Número de empresa (Taiwán)',
      fr: 'Numéro d’entreprise (Taïwan)',
      de: 'Taiwan-Unternehmensnummer',
    },
    blurb: {
      en: 'Validate a Taiwan Unified Business Number (統一編號).',
      'zh-TW': '驗證台灣公司統一編號。',
    },
  },
  {
    id: 'tw-arc',
    category: 'id',
    offline: true,
    markets: ['tw'],
    keywords: ['taiwan', 'arc', 'arc', '統一證號', 'resident', 'alien', 'validate'],
    name: {
      en: 'Taiwan ARC (統一證號)',
      'zh-TW': '外來人口統一證號',
      'zh-HK': '台灣統一證號',
    },
    blurb: {
      en: 'Validate a new-format Alien Resident Certificate number.',
      'zh-TW': '驗證新式外來人口統一證號。',
    },
  },
  {
    id: 'hk-salaries-tax',
    category: 'finance',
    offline: true,
    markets: ['hk'],
    keywords: ['hong kong', 'salaries tax', 'mpf', '薪俸稅', '強積金', 'take home', 'payroll', 'ird'],
    name: {
      en: 'HK salaries tax + MPF',
      'zh-HK': '薪俸稅 + 強積金',
      'zh-TW': '香港薪俸稅 + 強積金',
      ja: '香港給与税＋MPF',
      ko: '홍콩 급여세 + MPF',
      es: 'Impuesto salarial de HK + MPF',
      fr: 'Impôt sur salaire HK + MPF',
      de: 'HK-Gehaltssteuer + MPF',
    },
    blurb: {
      en: 'Estimate Hong Kong salaries tax, mandatory MPF, and take-home pay.',
      'zh-HK': '估算香港薪俸稅、強積金及稅後實收。',
    },
  },
  {
    id: 'hk-id',
    category: 'id',
    offline: true,
    markets: ['hk'],
    keywords: ['hong kong', 'hkid', '身份證', 'validate', 'identity'],
    name: {
      en: 'Hong Kong ID (HKID)',
      'zh-TW': '香港身份證驗證',
      'zh-HK': '香港身份證驗證',
      ja: '香港 ID（HKID）',
      ko: '홍콩 신분증 (HKID)',
      es: 'ID de Hong Kong (HKID)',
      fr: 'Carte d’identité de Hong Kong',
      de: 'Hongkong-ID (HKID)',
    },
    blurb: {
      en: 'Validate or generate a Hong Kong Identity Card number.',
      'zh-TW': '驗證或產生香港身份證號碼。',
    },
  },
  {
    id: 'hk-br',
    category: 'id',
    offline: true,
    markets: ['hk'],
    keywords: ['hong kong', 'br', 'brn', 'business registration', '商業登記', 'validate'],
    name: {
      en: 'Hong Kong BR number',
      'zh-TW': '香港商業登記號碼',
      'zh-HK': '商業登記號碼',
    },
    blurb: {
      en: 'Validate a Hong Kong Business Registration Number (8 digits).',
      'zh-HK': '驗證香港商業登記號碼（8 碼）。',
    },
  },
  {
    id: 'jp-furusato',
    category: 'finance',
    offline: true,
    markets: ['jp'],
    keywords: ['japan', 'furusato', 'hometown tax', 'ふるさと納税', '納税', '寄附', '控除', 'donation'],
    name: {
      en: 'Furusato tax limit',
      ja: 'ふるさと納税 上限額',
      'zh-TW': '日本故鄉稅上限',
      'zh-HK': '日本故鄉稅上限',
      ko: '후루사토 납세 한도',
      es: 'Límite furusato (Japón)',
      fr: 'Plafond furusato (Japon)',
      de: 'Furusato-Steuerlimit (Japan)',
    },
    blurb: {
      en: 'Estimate your ふるさと納税 hometown-tax donation ceiling.',
      ja: 'ふるさと納税の寄附上限額の目安を計算します。',
    },
  },
  {
    id: 'jp-mynumber',
    category: 'id',
    offline: true,
    markets: ['jp'],
    keywords: ['japan', 'my number', 'マイナンバー', 'validate', 'identity'],
    name: {
      en: 'Japan My Number',
      'zh-TW': '日本 My Number',
      'zh-HK': '日本 My Number',
      ja: 'マイナンバー検証',
      ko: '일본 마이넘버',
      es: 'My Number (Japón)',
      fr: 'My Number (Japon)',
      de: 'My Number (Japan)',
    },
    blurb: {
      en: 'Validate or generate a Japanese My Number (マイナンバー).',
      'zh-TW': '驗證或產生日本個人編號。',
    },
  },
  {
    id: 'jp-corp-number',
    category: 'id',
    offline: true,
    markets: ['jp'],
    keywords: ['japan', 'corporate number', '法人番号', 'invoice', 'インボイス'],
    name: {
      en: 'Japan Corporate / Invoice №',
      'zh-TW': '日本法人／發票番號',
      'zh-HK': '日本法人／發票番號',
      ja: '法人番号検証',
      ko: '일본 법인번호/인보이스',
      es: 'Número corporativo (Japón)',
      fr: 'Numéro d’entreprise (Japon)',
      de: 'Firmen-/Rechnungsnummer (Japan)',
    },
    blurb: {
      en: 'Validate a Japanese Corporate Number or qualified Invoice number.',
      'zh-TW': '驗證日本法人番號或合格發票番號。',
    },
  },

  // --- Market packs (Phase 3, batch 2) — postal / phone / financial formats. ---
  {
    id: 'us-ssn',
    category: 'id',
    offline: true,
    markets: ['en-us'],
    keywords: ['usa', 'us', 'ssn', 'social security', 'validate'],
    name: {
      en: 'US Social Security Number',
      'zh-TW': '美國社會安全碼 (SSN)',
      'zh-HK': '美國社會安全號碼 (SSN)',
      ja: '米国社会保障番号 (SSN)',
      ko: '미국 사회보장번호 (SSN)',
      es: 'Número de Seguro Social (EE. UU.)',
      fr: 'Numéro de sécurité sociale (USA)',
      de: 'US-Sozialversicherungsnummer (SSN)',
    },
    blurb: {
      en: 'Check that a US SSN has a valid format and reserved ranges.',
      'zh-TW': '檢查美國 SSN 的格式與保留範圍是否有效。',
    },
  },
  {
    id: 'us-zip',
    category: 'id',
    offline: true,
    markets: ['en-us'],
    keywords: ['usa', 'us', 'zip', 'postal', 'zip+4', 'validate'],
    name: {
      en: 'US ZIP code',
      'zh-TW': '美國郵遞區號 (ZIP)',
      'zh-HK': '美國郵遞區號 (ZIP)',
      ja: '米国 ZIP コード',
      ko: '미국 우편번호 (ZIP)',
      es: 'Código ZIP (EE. UU.)',
      fr: 'Code ZIP (USA)',
      de: 'US-ZIP-Code',
    },
    blurb: {
      en: 'Check a US ZIP or ZIP+4 code format.',
      'zh-TW': '檢查美國 ZIP 或 ZIP+4 格式。',
    },
  },
  {
    id: 'us-routing',
    category: 'id',
    offline: true,
    markets: ['en-us'],
    keywords: ['usa', 'us', 'aba', 'routing', 'bank', 'transit', 'validate'],
    name: {
      en: 'US bank routing number (ABA)',
      'zh-TW': '美國銀行路由號碼 (ABA)',
      'zh-HK': '美國銀行路由號碼 (ABA)',
      ja: '米国銀行ルーティング番号 (ABA)',
      ko: '미국 은행 라우팅 번호 (ABA)',
      es: 'Número de ruta bancaria (ABA)',
      fr: 'Numéro de routage bancaire (ABA)',
      de: 'US-Bankleitzahl (ABA)',
    },
    blurb: {
      en: 'Validate a US ABA routing transit number (checksum).',
      'zh-TW': '驗證美國 ABA 路由號碼（檢查碼）。',
    },
  },
  {
    id: 'jp-postal',
    category: 'id',
    offline: true,
    markets: ['jp'],
    keywords: ['japan', 'postal', '郵便番号', 'zip', 'validate'],
    name: {
      en: 'Japan postal code',
      'zh-TW': '日本郵遞區號',
      'zh-HK': '日本郵遞區號',
      ja: '日本の郵便番号',
      ko: '일본 우편번호',
      es: 'Código postal (Japón)',
      fr: 'Code postal (Japon)',
      de: 'Japanische Postleitzahl',
    },
    blurb: {
      en: 'Check a Japanese postal code format (〒NNN-NNNN).',
      'zh-TW': '檢查日本郵遞區號格式（〒NNN-NNNN）。',
    },
  },
  {
    id: 'hk-phone',
    category: 'id',
    offline: true,
    markets: ['hk'],
    keywords: ['hong kong', 'phone', 'telephone', 'mobile', '電話', 'validate'],
    name: {
      en: 'Hong Kong phone number',
      'zh-TW': '香港電話號碼',
      'zh-HK': '香港電話號碼',
      ja: '香港の電話番号',
      ko: '홍콩 전화번호',
      es: 'Teléfono de Hong Kong',
      fr: 'Téléphone de Hong Kong',
      de: 'Hongkong-Telefonnummer',
    },
    blurb: {
      en: 'Check an 8-digit Hong Kong phone number format.',
      'zh-TW': '檢查香港 8 位電話號碼格式。',
    },
  },
  {
    id: 'tw-mobile',
    category: 'id',
    offline: true,
    markets: ['tw'],
    keywords: ['taiwan', 'mobile', 'phone', '手機', '09', 'validate'],
    name: {
      en: 'Taiwan mobile number',
      'zh-TW': '台灣手機號碼',
      'zh-HK': '台灣手機號碼',
      ja: '台湾の携帯電話番号',
      ko: '대만 휴대폰 번호',
      es: 'Móvil de Taiwán',
      fr: 'Mobile de Taïwan',
      de: 'Taiwanische Handynummer',
    },
    blurb: {
      en: 'Check a Taiwan mobile number format (09XXXXXXXX).',
      'zh-TW': '檢查台灣手機號碼格式（09XXXXXXXX）。',
    },
  },

  // --- Market packs (Phase 3, batch 3) — more US formats + new UK market. ---
  {
    id: 'us-ein',
    category: 'id',
    offline: true,
    markets: ['en-us'],
    keywords: ['usa', 'us', 'ein', 'employer', 'tax id', 'irs', 'validate'],
    name: {
      en: 'US Employer ID Number (EIN)',
      'zh-TW': '美國雇主識別號 (EIN)',
      'zh-HK': '美國雇主識別號 (EIN)',
      ja: '米国雇用者番号 (EIN)',
      ko: '미국 고용주 식별번호 (EIN)',
      es: 'Número de empleador (EIN)',
      fr: 'Numéro d’employeur (EIN)',
      de: 'US-Arbeitgebernummer (EIN)',
    },
    blurb: {
      en: 'Check a US EIN format and IRS campus prefix.',
      'zh-TW': '檢查美國 EIN 格式與 IRS 前綴。',
    },
  },
  {
    id: 'us-phone',
    category: 'id',
    offline: true,
    markets: ['en-us'],
    keywords: ['usa', 'us', 'phone', 'nanp', 'telephone', 'validate'],
    name: {
      en: 'US phone number',
      'zh-TW': '美國電話號碼',
      'zh-HK': '美國電話號碼',
      ja: '米国の電話番号',
      ko: '미국 전화번호',
      es: 'Teléfono de EE. UU.',
      fr: 'Téléphone (USA)',
      de: 'US-Telefonnummer',
    },
    blurb: {
      en: 'Check a North American (NANP) phone number format.',
      'zh-TW': '檢查北美 (NANP) 電話號碼格式。',
    },
  },
  {
    id: 'uk-postcode',
    category: 'id',
    offline: true,
    markets: ['en-gb'],
    keywords: ['uk', 'britain', 'postcode', 'postal', 'validate'],
    name: {
      en: 'UK postcode',
      'zh-TW': '英國郵遞區號',
      'zh-HK': '英國郵遞區號',
      ja: '英国の郵便番号',
      ko: '영국 우편번호',
      es: 'Código postal (Reino Unido)',
      fr: 'Code postal (Royaume-Uni)',
      de: 'Britische Postleitzahl',
    },
    blurb: {
      en: 'Check a UK postcode format (e.g. SW1A 1AA).',
      'zh-TW': '檢查英國郵遞區號格式（例如 SW1A 1AA）。',
    },
  },
  {
    id: 'uk-nino',
    category: 'id',
    offline: true,
    markets: ['en-gb'],
    keywords: ['uk', 'britain', 'national insurance', 'nino', 'ni number', 'validate'],
    name: {
      en: 'UK National Insurance number',
      'zh-TW': '英國國民保險號碼 (NINO)',
      'zh-HK': '英國國民保險號碼 (NINO)',
      ja: '英国国民保険番号 (NINO)',
      ko: '영국 국민보험번호 (NINO)',
      es: 'Número de Seguro Nacional (Reino Unido)',
      fr: 'Numéro d’assurance nationale (Royaume-Uni)',
      de: 'Britische Sozialversicherungsnummer (NINO)',
    },
    blurb: {
      en: 'Check a UK National Insurance number format and prefix.',
      'zh-TW': '檢查英國國民保險號碼格式與前綴。',
    },
  },
  {
    id: 'uk-sort-code',
    category: 'id',
    offline: true,
    markets: ['en-gb'],
    keywords: ['uk', 'britain', 'sort code', 'bank', 'validate'],
    name: {
      en: 'UK bank sort code',
      'zh-TW': '英國銀行分行代碼',
      'zh-HK': '英國銀行分行代碼',
      ja: '英国銀行ソートコード',
      ko: '영국 은행 소트 코드',
      es: 'Sort code bancario (Reino Unido)',
      fr: 'Sort code bancaire (Royaume-Uni)',
      de: 'Britische Bankleitzahl (Sort Code)',
    },
    blurb: {
      en: 'Check a UK bank sort code format (XX-XX-XX).',
      'zh-TW': '檢查英國銀行分行代碼格式（XX-XX-XX）。',
    },
  },
  {
    id: 'tw-postal',
    category: 'id',
    offline: true,
    markets: ['tw'],
    keywords: ['taiwan', 'postal', '郵遞區號', 'zip', 'validate'],
    name: {
      en: 'Taiwan postal code',
      'zh-TW': '台灣郵遞區號',
      'zh-HK': '台灣郵遞區號',
      ja: '台湾の郵便番号',
      ko: '대만 우편번호',
      es: 'Código postal (Taiwán)',
      fr: 'Code postal (Taïwan)',
      de: 'Taiwanische Postleitzahl',
    },
    blurb: {
      en: 'Check a Taiwan postal code format (3, 3+2 or 3+3 digits).',
      'zh-TW': '檢查台灣郵遞區號格式（3 碼、3+2 或 3+3）。',
    },
  },
];

/** A small accent colour per tool category, shared by the grid, cards, sidebar, and prerender. */
export const CATEGORY_COLOR: Record<string, string> = {
  pdf: '#ef5350',
  image: '#ab47bc',
  text: '#26a69a',
  calc: '#42a5f5',
  convert: '#5c6bc0',
  datetime: '#ec407a',
  id: '#7e57c2',
  finance: '#66bb6a',
  generator: '#ffa726',
  dev: '#8d6e63',
  daily: '#29b6f6',
  file: '#78909c',
};

/** Resolve a category's accent colour, falling back to the app accent. */
export function categoryColor(category: string): string {
  return CATEGORY_COLOR[category] ?? 'var(--accent)';
}

/** All tool ids, in catalogue order. */
export const CATALOG_IDS: readonly string[] = CATALOG.map((t) => t.id);

const BY_ID: ReadonlyMap<string, CatalogTool> = new Map(CATALOG.map((t) => [t.id, t]));

export function getTool(id: string): CatalogTool | undefined {
  return BY_ID.get(id);
}

function pick(map: L10n, lang: Lang): string {
  return map[lang] ?? map.en;
}

/** Localized display name for a tool id, falling back to English then the id. */
export function localizedName(id: string, lang: Lang): string {
  const tool = BY_ID.get(id);
  return tool ? pick(tool.name, lang) : id;
}

/** Localized one-line description for a tool id, falling back to English. */
export function localizedBlurb(id: string, lang: Lang): string {
  const tool = BY_ID.get(id);
  return tool ? pick(tool.blurb, lang) : '';
}
