import type { Lang } from './i18n';

/**
 * Supplementary tool-name translations layered on top of the catalogue, keeping
 * catalog.ts tidy while filling gaps. Currently completes Japanese (a primary
 * market) plus two zh-HK region names.
 *
 * Intentionally absent — these read the same in every language and stay English
 * by design: format names (JSON ↔ CSV, JSON ↔ YAML, XML ↔ JSON, CSV ↔ Excel,
 * HEIC → JPG) and bare algorithm identifiers (ROT13, ROT47, Soundex,
 * Quoted-printable).
 */
export const NAME_OVERRIDES: Partial<Record<Lang, Readonly<Record<string, string>>>> = {
  ja: {
    'qr-batch': 'QRコード一括生成',
    'csv-clean': 'CSVクリーナー',
    slugify: 'スラグ生成',
    'lorem-ipsum': 'ダミーテキスト生成',
    'line-dedupe': '重複行を削除',
    'sort-lines': '行の並べ替え',
    'text-normalize': 'テキストを正規化',
    'reverse-text': 'テキストを反転',
    hmac: 'HMAC生成',
    'random-string': 'ランダム文字列生成',
    'roman-numeral': 'ローマ数字',
    'data-size': 'データ容量変換',
    'find-replace': '検索と置換',
    'extract-urls': 'メール・URLを抽出',
    'shuffle-lines': '行をシャッフル',
    'word-frequency': '単語の頻度',
    'area-convert': '面積変換',
    'speed-convert': '速度変換',
    'json-escape': 'JSON文字列エスケープ',
    nanoid: 'NanoID生成',
    totp: 'TOTPコード',
    'trim-lines': '行の前後の空白を除去',
    'remove-empty-lines': '空行を削除',
    'number-lines': '行番号を付与',
    'text-wrap': 'テキストの折り返し',
    'morse-code': 'モールス信号',
    'binary-text': 'テキスト ↔ バイナリ',
    levenshtein: 'レーベンシュタイン距離',
    'strip-html': 'HTMLタグを除去',
    'pressure-convert': '圧力変換',
    'timestamp-convert': 'Unixタイムスタンプ',
    'repeat-text': 'テキストを繰り返し',
    'join-lines': '行を結合',
    'split-text': '行に分割',
    'caesar-cipher': 'シーザー暗号',
    'remove-diacritics': 'アクセント記号を除去',
    'palindrome-check': '回文チェッカー',
    'grep-lines': '行を抽出（grep）',
    'indent-lines': '行をインデント',
    'energy-convert': 'エネルギー変換',
    'duration-format': '経過時間の書式',
    'hex-text': 'テキスト ↔ 16進数',
    'unicode-escape': 'Unicodeエスケープ',
    'reverse-words': '単語を逆順',
    'tabs-spaces': 'タブ ↔ スペース',
    'hamming-distance': 'ハミング距離',
    'volume-convert': '体積変換',
    'angle-convert': '角度変換',
    'char-frequency': '文字の頻度',
    'line-prefix': '各行に接頭辞・接尾辞',
    'mass-convert': '質量変換',
    'temperature-convert': '温度変換',
    'power-convert': '仕事率変換',
    'frequency-convert': '周波数変換',
    'truncate-text': 'テキストを切り詰め',
    'pad-text': 'テキストをパディング',
    'zero-width-clean': 'ゼロ幅文字を除去',
    'markdown-strip': 'Markdownを除去',
    'atbash-cipher': 'アトバシュ暗号',
    'base32-codec': 'Base32 エンコード / デコード',
    'length-convert': '長さ変換',
    'jaccard-similarity': 'ジャカード類似度',
    'extract-numbers': '数値を抽出',
    'extract-ipv4': 'IPv4を抽出',
    'transpose-grid': '表を転置',
    'gcd-lcm': '最大公約数・最小公倍数',
    'string-similarity': '文字列の類似度',
    'mask-emails': 'メールアドレスをマスク',
    'audio-extract': '音声を抽出',
    'images-to-pdf': '画像をPDFに',
    'pdf-to-images': 'PDFを画像に',
    'docx-to-pdf': 'WordをPDFに',
    'pptx-to-pdf': 'PowerPointをPDFに',
    'pdf-to-word': 'PDFをWordに',
    'ca-sin': 'カナダ社会保険番号（SIN）',
    'au-tfn': 'オーストラリア税務番号（TFN）',
    'tw-arc': '台湾ARC（統一証号）',
    'hk-br': '香港事業登録番号（BR）',
  },
  'zh-HK': {
    'ca-sin': '加拿大社會保險號碼（SIN）',
    'au-tfn': '澳洲稅務檔案號碼（TFN）',
  },
};
